//                              _       _
//                           __| | ___ | |__   __ _
//                          / _` |/ _ \| '_ \ / _` |
//                         | (_| | (_) | |_) | (_| |
//                          \__,_|\___/|_.__/ \__,_|
//
//                              Apache License
//                        Version 2.0, January 2004
//                     http://www.apache.org/licenses/
//
// Copyright 2025 martianLabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

#ifndef martianlabs_doba_protocol_http11_headers_acrm_h
#define martianlabs_doba_protocol_http11_headers_acrm_h

#include "protocol/http11/helpers.h"

namespace martianlabs::doba::protocol::http11::headers {
// /////////////////////////////////////////////////////////////////////////////
// +===========================================================================+
// |                                             access-control-request-method |
// +===========================================================================+
// | Fetch �3.3.2 Access-Control-Request-Method                                |
// +---------------------------------------------------------------------------+
// | The "Access-Control-Request-Method" request header field is used by a     |
// | user agent in a CORS-preflight request to indicate which HTTP method a    |
// | future CORS request to the same resource might use.                       |
// |                                                                           |
// | A CORS-preflight request uses the OPTIONS method, so this field carries   |
// | the method intended for the actual request rather than the method of the  |
// | preflight request itself.                                                 |
// |                                                                           |
// | This field is generated by user agents as part of the CORS protocol. It   |
// | contains exactly one HTTP method token. It is not a list field.           |
// |                                                                           |
// | The method token is case-sensitive. By convention, standardized HTTP      |
// | methods are defined using uppercase US-ASCII letters, such as GET, POST,  |
// | PUT, PATCH, or DELETE.                                                    |
// |                                                                           |
// | Pure ABNF validation only checks that the field value is a valid HTTP     |
// | method token. It does not check whether the method is registered, allowed,|
// | implemented by the server, or permitted by the CORS policy.               |
// |                                                                           |
// | Examples:                                                                 |
// |   Access-Control-Request-Method: POST                                     |
// |   Access-Control-Request-Method: PUT                                      |
// |   Access-Control-Request-Method: DELETE                                   |
// +---------------------------------------------------------------------------+
// | Fetch �3.3.4 HTTP new-header syntax + RFC 9110 �9.1 Method (ABNF summary) |
// +---------------------------------------------------------------------------+
// +-------------------------------+-------------------------------------------+
// | Field                         | Definition                                |
// +-------------------------------+-------------------------------------------+
// | Access-Control-Request-Method | method                                    |
// | method                        | token                                     |
// | token                         | 1*tchar                                   |
// | tchar                         | "!" / "#" / "$" / "%" / "&" / "'" /       |
// |                               | "*" / "+" / "-" / "." / "^" / "_" /       |
// |                               | "`" / "|" / "~" / DIGIT / ALPHA           |
// | OWS                           | *( SP / HTAB )                            |
// +---------------------------------------------------------------------------+
// | Notes                                                                     |
// +---------------------------------------------------------------------------+
// | This field is not defined using the HTTP list extension. Therefore, comma |
// | separated values are not valid for this field.                            |
// |                                                                           |
// | Empty values are invalid because "method" expands to "token", and "token" |
// | requires at least one tchar.                                              |
// +---------------------------------------------------------------------------+
// | IMPORTANT: field-value is supposed to be normalized (no OWS around value).|
// +---------------------------------------------------------------------------+
// /////////////////////////////////////////////////////////////////////////////
class access_control_request_method {
 public:
  // +=========================================================================+
  // | [>] check                                                    ( public ) |
  // +=========================================================================+
  static constexpr bool check(std::string_view sv) {
    // Access-Control-Request-Method = method = token = 1*tchar. It is not a
    // list field, so the whole (normalized) value must be exactly one token.
    return helpers::is_token(sv);
  }
};
}  // namespace martianlabs::doba::protocol::http11::headers

#endif
