language:
  version: 20
  engines:
    default:
      command: /opt/web/build/doba_web_frameworks_http_v11

framework:
  website: https://github.com/martianlabs/doba
  github: https://github.com/martianlabs/doba
  version: 0.1.0
  engines:
    - default
  binaries:
    - build/doba_web_frameworks_http_v11
  download:
    - git init doba
    - >-
      git -C doba fetch --depth=1
      https://github.com/martianlabs/doba.git
      7be948e437e9bf8c1dcbf88bcaae9e4c5112f093
    - git -C doba checkout --detach FETCH_HEAD
  build:
    - mkdir build
    - cd build && cmake -DCMAKE_BUILD_TYPE=Release -DDOBA_INCLUDE_DIR=/usr/src/app/doba/include ..
    - cd build && make
