name: CI

on:
  pull_request:
  merge_group:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ubuntu:
    name: CI (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: >-
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_COMPILER=g++

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

  windows:
    name: CI (windows-latest)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: cmake --preset msvc-debug

      - name: Build
        run: cmake --build --preset build-debug

      - name: Test
        run: ctest --test-dir out/build/msvc-debug --output-on-failure
